---
- name: Install packages
  hosts: all
  become: true

  tasks:
    - name: Install git
      ansible.builtin.dnf:
        name: git
        state: present

    - name: Install nginx
      ansible.builtin.dnf:
        name: nginx
        state: present