---
- name: Manage services
  hosts: all
  become: true

  tasks:
    - name: Enable nginx
      ansible.builtin.service:
        name: nginx
        enabled: true
        state: started

    - name: Enable sshd
      ansible.builtin.copy:
        src: sshd.service
        dest: /etc/systemd/system/sshd.service
      notify:
        - Restart sshd